export interface PilgrimagePlace {
  id: string;
  name: string;
  location: string;
  religion: "Hindu" | "Muslim" | "Sikh" | "Buddhist" | "Christian" | "Jain";
  description: string;
  image: string;
  lat: number;
  lng: number;
  significance: string;
  bestTimeToVisit: string;
}

export const pilgrimagePlaces: PilgrimagePlace[] = [
  // Hindu
  {
  id: "yamunotri",
  name: "Yamunotri Temple",
  location: "Uttarkashi, Uttarakhand",
  religion: "Hindu",
  description: "Sacred temple dedicated to Goddess Yamuna and the source of River Yamuna",
  image: "/ya.jpg",
  lat: 31.0140,
  lng: 78.4600,
  significance: "First stop of the Char Dham Yatra and an important site for seeking blessings of Goddess Yamuna",
  bestTimeToVisit: "May to June and September to October",
},
{
  "id": "ram-mandir-ayodhya",
  "name": "Shri Ram Janmabhoomi Mandir",
  "location": "Ayodhya, Uttar Pradesh",
  "religion": "Hindu",
  "description": "Grand temple dedicated to Lord Ram built at his traditional birthplace",
  "image": "/rammm.jpg",
  "lat": 26.7956,
  "lng": 82.1943,
  "significance": "Believed to mark the birthplace of Lord Ram; one of the most important Hindu pilgrimage sites",
  "bestTimeToVisit": "October to March"
},

{
  id: "gangotri",
  name: "Gangotri Temple",
  location: "Uttarkashi, Uttarakhand",
  religion: "Hindu",
  description: "Sacred shrine dedicated to Goddess Ganga, origin point of the River Ganges",
  image: "/Gangotri.jpg",
  lat: 30.9947,
  lng: 78.9398,
  significance: "Second stop of the Char Dham Yatra and sacred source of the holy River Ganga",
  bestTimeToVisit: "May to June and September to October",
},

{
  id: "kedarnath",
  name: "Kedarnath Temple",
  location: "Rudraprayag, Uttarakhand",
  religion: "Hindu",
  description: "Ancient temple dedicated to Lord Shiva and one of the twelve Jyotirlingas",
  image: "/kedarnath.jpeg",
  lat: 30.7352,
  lng: 79.0669,
  significance: "One of the holiest Shiva temples and a major pilgrimage site in the Himalayas",
  bestTimeToVisit: "May to June and September to October",
},

{
  id: "badrinath",
  name: "Badrinath Temple",
  location: "Chamoli, Uttarakhand",
  religion: "Hindu",
  description: "Sacred temple dedicated to Lord Vishnu in his form as Badrinarayan",
  image: "/badrinath.jpg",
  lat: 30.7433,
  lng: 79.4938,
  significance: "Final stop of the Char Dham Yatra and one of the most important Vaishnav pilgrimage sites in India",
  bestTimeToVisit: "May to June and September to October",
},

  {
    id: "varanasi",
    name: "Kashi Vishwanath Temple",
    location: "Varanasi, Uttar Pradesh",
    religion: "Hindu",
    description: "One of the twelve Jyotirlingas, the most sacred Shiva temple",
    image: "/Varanasi.jpg",
    lat: 25.3176,
    lng: 82.9739,
    significance: "Holiest of Hindu pilgrimage sites on the banks of Ganges",
    bestTimeToVisit: "October to March",
  },
  {
    id: "tirupati",
    name: "Tirumala Venkateswara Temple",
    location: "Tirupati, Andhra Pradesh",
    religion: "Hindu",
    description: "Richest and most visited temple dedicated to Lord Venkateswara",
    image: "/tirupati.jpg",
    lat: 13.6833,
    lng: 79.3472,
    significance: "Abode of Lord Venkateswara, believed to grant wishes",
    bestTimeToVisit: "September to February",
  },
  {
    id: "golden-temple",
    name: "Harmandir Sahib (Golden Temple)",
    location: "Amritsar, Punjab",
    religion: "Sikh",
    description: "The most sacred Gurdwara of Sikhism",
    image: "/harmandir.jpg",
    lat: 31.6200,
    lng: 74.8765,
    significance: "Spiritual and cultural center of Sikhism",
    bestTimeToVisit: "November to March",
  },
  {
    id: "bodh-gaya",
    name: "Mahabodhi Temple",
    location: "Bodh Gaya, Bihar",
    religion: "Buddhist",
    description: "Place where Buddha attained enlightenment",
    image: "/bodh.jpg",
    lat: 24.6958,
    lng: 84.9910,
    significance: "Most sacred site in Buddhism, UNESCO World Heritage",
    bestTimeToVisit: "October to March",
  },
  {
    id: "ajmer-sharif",
    name: "Ajmer Sharif Dargah",
    location: "Ajmer, Rajasthan",
    religion: "Muslim",
    description: "Sufi shrine of Moinuddin Chishti",
    image: "/ajmer.jpg",
    lat: 26.4499,
    lng: 74.6399,
    significance: "One of the holiest Islamic shrines in India",
    bestTimeToVisit: "October to March",
  },
  {
    id: "jagannath-puri",
    name: "Jagannath Temple",
    location: "Puri, Odisha",
    religion: "Hindu",
    description: "Famous for the annual Rath Yatra festival",
    image: "/pr.jpg",
    lat: 19.8135,
    lng: 85.8312,
    significance: "Part of Char Dham, dedicated to Lord Jagannath",
    bestTimeToVisit: "October to March",
  },
  {
    id: "rameshwaram",
    name: "Ramanathaswamy Temple",
    location: "Rameswaram, Tamil Nadu",
    religion: "Hindu",
    description: "One of the twelve Jyotirlinga temples",
    image: "/ram.jpg",
    lat: 9.2876,
    lng: 79.3129,
    significance: "Part of Char Dham, where Lord Rama worshipped Shiva",
    bestTimeToVisit: "October to April",
  },
  {
    id: "dwarka",
    name: "Dwarkadhish Temple",
    location: "Dwarka, Gujarat",
    religion: "Hindu",
    description: "Ancient Krishna temple, part of Char Dham",
    image: "/dwar.jpg",
    lat: 22.2442,
    lng: 68.9685,
    significance: "Kingdom of Lord Krishna",
    bestTimeToVisit: "October to March",
  },
  {
    id: "velankanni",
    name: "Basilica of Our Lady of Good Health",
    location: "Velankanni, Tamil Nadu",
    religion: "Christian",
    description: "Major Catholic pilgrimage site",
    image: "/joir.jpg",
    lat: 10.6833,
    lng: 79.8500,
    significance: "Miracles attributed to Virgin Mary",
    bestTimeToVisit: "August to September",
  },
  {
    id: "hemkund-sahib",
    name: "Hemkund Sahib",
    location: "Chamoli, Uttarakhand",
    religion: "Sikh",
    description: "High altitude Sikh pilgrimage site",
    image: "/hemkund.jpg",
    lat: 30.7268,
    lng: 79.7325,
    significance: "Where Guru Gobind Singh meditated",
    bestTimeToVisit: "June to October",
  },
  {
  id: "jama-masjid-delhi",
  name: "Jama Masjid",
  location: "Delhi, India",
  religion: "Muslim",
  description: "One of the largest mosques in India built during the Mughal era",
  image: "/jama.jpg",
  lat: 28.6507,
  lng: 77.2334,
  significance: "Built by Shah Jahan; major center for Friday and Eid prayers",
  bestTimeToVisit: "October to March"
},
{
  id: "haji-ali-dargah",
  name: "Haji Ali Dargah",
  location: "Mumbai, Maharashtra",
  religion: "Muslim",
  description: "Iconic dargah located on an islet off the Mumbai coast",
  image: "/haji ali.jpg",
  lat: 18.9828,
  lng: 72.8089,
  significance: "Dedicated to Pir Haji Ali Shah Bukhari; major pilgrimage site",
  bestTimeToVisit: "November to February"
},
{
  id: "hazratbal-shrine",
  name: "Hazratbal Shrine",
  location: "Srinagar, Jammu and Kashmir",
  religion: "Muslim",
  description: "Sacred shrine housing a relic believed to be a hair of Prophet Muhammad",
  image: "/hazra.jpg",
  lat: 34.1256,
  lng: 74.8370,
  significance: "Most revered Muslim shrine in Kashmir",
  bestTimeToVisit: "April to October"
},
{
  id: "charminar-mosque",
  name: "Charminar Mosque",
  location: "Hyderabad, Telangana",
  religion: "Muslim",
  description: "Historic mosque located within the Charminar monument",
  image: "/charminar.jpg",
  lat: 17.3616,
  lng: 78.4747,
  significance: "Built by Muhammad Quli Qutb Shah; cultural and religious landmark",
  bestTimeToVisit: "October to February"
},
{
  id: "tipu-sultan-mosque",
  name: "Tipu Sultan Mosque",
  location: "Kolkata, West Bengal",
  religion: "Muslim",
  description: "Prominent mosque built in the 19th century in central Kolkata",
  image: "/tipu sultan.jpg",
  lat: 22.5726,
  lng: 88.3639,
  significance: "Named after Tipu Sultan; important Sunni mosque in eastern India",
  bestTimeToVisit: "October to March"
},
 {
    "id": "palitana-temples",
    "name": "Shatrunjaya Temples",
    "location": "Palitana, Gujarat",
    "religion": "Jain",
    "description": "Sacred hill complex with hundreds of intricately carved Jain temples",
    "image": "/shatrunjay.jpg",
    "lat": 21.5254,
    "lng": 71.8235,
    "significance": "One of the holiest pilgrimage sites in Jainism dedicated primarily to Rishabhanatha",
    "bestTimeToVisit": "November to February"
  },
  {
    "id": "dilwara-temples",
    "name": "Dilwara Temples",
    "location": "Mount Abu, Rajasthan",
    "religion": "Jain",
    "description": "Famous marble Jain temples known for extraordinary architecture and carvings",
    "image": "/dilware.jpg",
    "lat": 24.5926,
    "lng": 72.7156,
    "significance": "Important Svetambara Jain pilgrimage site built between 11th and 13th centuries",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "shravanabelagola",
    "name": "Shravanabelagola",
    "location": "Hassan, Karnataka",
    "religion": "Jain",
    "description": "Historic Jain pilgrimage center known for the giant monolithic statue of Bahubali",
    "image": "/shravan bela.jpg",
    "lat": 12.8578,
    "lng": 76.4888,
    "significance": "Major Digambara Jain site; hosts the Mahamastakabhisheka festival",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "ranakpur-jain-temple",
    "name": "Ranakpur Jain Temple",
    "location": "Ranakpur, Rajasthan",
    "religion": "Jain",
    "description": "Magnificent temple complex dedicated to Tirthankara Adinatha",
    "image": "/ranakpur jain.jpg",
    "lat": 25.1163,
    "lng": 73.4723,
    "significance": "Renowned for its 1,444 uniquely carved marble pillars",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "girnar-jain-temples",
    "name": "Girnar Jain Temples",
    "location": "Junagadh, Gujarat",
    "religion": "Jain",
    "description": "Ancient Jain temples located on Mount Girnar after a steep pilgrimage climb",
    "image": "/girnar jain.jpg",
    "lat": 21.5222,
    "lng": 70.5290,
    "significance": "Sacred site associated with Tirthankara Neminatha",
    "bestTimeToVisit": "November to February"
  },
  {
    "id": "sonagiri-jain-temples",
    "name": "Sonagiri Jain Temples",
    "location": "Datia, Madhya Pradesh",
    "religion": "Jain",
    "description": "Hilltop temple complex with numerous white Jain shrines",
    "image": "/sonagiri.jpg",
    "lat": 25.6722,
    "lng": 78.4594,
    "significance": "Important Digambara Jain pilgrimage site with over 100 temples",
    "bestTimeToVisit": "October to March"
  },
   {
    "id": "velankanni-basilica",
    "name": "Basilica of Our Lady of Good Health",
    "location": "Velankanni, Tamil Nadu",
    "religion": "Christian",
    "description": "Famous Marian shrine known as the 'Lourdes of the East'",
    "image": "/lady of good health.jpg",
    "lat": 10.6833,
    "lng": 79.8529,
    "significance": "Major Catholic pilgrimage center dedicated to Our Lady of Good Health",
    "bestTimeToVisit": "August to September"
  },
  {
    "id": "bom-jesus-basilica",
    "name": "Basilica of Bom Jesus",
    "location": "Old Goa, Goa",
    "religion": "Christian",
    "description": "UNESCO World Heritage church housing the mortal remains of St. Francis Xavier",
    "image": "/bom jesus.jpg",
    "lat": 15.5009,
    "lng": 73.9115,
    "significance": "One of the oldest churches in India and an important Catholic pilgrimage site",
    "bestTimeToVisit": "November to February"
  },
  {
    "id": "santhome-cathedral",
    "name": "Santhome Cathedral Basilica",
    "location": "Chennai, Tamil Nadu",
    "religion": "Christian",
    "description": "Historic cathedral built over the tomb of St. Thomas the Apostle",
    "image": "/santhome.jpg",
    "lat": 13.0338,
    "lng": 80.2778,
    "significance": "One of the three churches in the world built over the tomb of an apostle",
    "bestTimeToVisit": "November to February"
  },
  {
    "id": "st-francis-church-kochi",
    "name": "St. Francis Church",
    "location": "Kochi, Kerala",
    "religion": "Christian",
    "description": "One of the oldest European churches in India",
    "image": "/st. fransis.jpg",
    "lat": 9.9667,
    "lng": 76.2425,
    "significance": "Historic church where Vasco da Gama was originally buried",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "se-cathedral-goa",
    "name": "Se Cathedral",
    "location": "Old Goa, Goa",
    "religion": "Christian",
    "description": "One of the largest churches in Asia built during Portuguese rule",
    "image": "/cathedral.jpg",
    "lat": 15.5010,
    "lng": 73.9120,
    "significance": "Dedicated to St. Catherine of Alexandria; major Catholic landmark",
    "bestTimeToVisit": "November to February"
  },
  {
    "id": "medak-cathedral",
    "name": "Medak Cathedral",
    "location": "Medak, Telangana",
    "religion": "Christian",
    "description": "Impressive Gothic-style cathedral and one of the largest in India",
    "image": "/medak.jpg",
    "lat": 18.0450,
    "lng": 78.2600,
    "significance": "Prominent Protestant church and architectural landmark",
    "bestTimeToVisit": "October to February"
  },
  {
    "id": "mahabodhi-temple",
    "name": "Mahabodhi Temple",
    "location": "Bodh Gaya, Bihar",
    "religion": "Buddhist",
    "description": "Sacred temple marking the place where Gautama Buddha attained enlightenment",
    "image": "/mahabodhi.jpg",
    "lat": 24.6951,
    "lng": 84.9910,
    "significance": "UNESCO World Heritage Site and the holiest Buddhist pilgrimage destination",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "sarnath-dhamek-stupa",
    "name": "Dhamek Stupa",
    "location": "Sarnath, Uttar Pradesh",
    "religion": "Buddhist",
    "description": "Ancient stupa marking the site of Buddha’s first sermon",
    "image": "/dhamek stupt.jpg",
    "lat": 25.3810,
    "lng": 83.0210,
    "significance": "Commemorates the 'Dhammacakkappavattana Sutta' (First Sermon)",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "kushinagar-mahaparinirvana",
    "name": "Mahaparinirvana Temple",
    "location": "Kushinagar, Uttar Pradesh",
    "religion": "Buddhist",
    "description": "Temple housing the reclining Buddha statue marking his final passing",
    "image": "/mahaparinirvanu.jpg",
    "lat": 26.7397,
    "lng": 83.8889,
    "significance": "Site where Gautama Buddha attained Mahaparinirvana",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "rajgir-vulture-peak",
    "name": "Vulture’s Peak (Gridhrakuta Hill)",
    "location": "Rajgir, Bihar",
    "religion": "Buddhist",
    "description": "Sacred hill where Buddha delivered many important sermons",
    "image": "/vulture's.jpg",
    "lat": 25.0110,
    "lng": 85.4200,
    "significance": "Associated with the teaching of the Lotus Sutra and other discourses",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "nalanda-mahavihara",
    "name": "Nalanda Mahavihara",
    "location": "Nalanda, Bihar",
    "religion": "Buddhist",
    "description": "Ancient monastic university and major center of Buddhist learning",
    "image": "/nalanda.jpg",
    "lat": 25.1367,
    "lng": 85.4449,
    "significance": "Historic seat of Mahayana Buddhist scholarship",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "tawang-monastery",
    "name": "Tawang Monastery",
    "location": "Tawang, Arunachal Pradesh",
    "religion": "Buddhist",
    "description": "Largest monastery in India and an important center of Tibetan Buddhism",
    "image": "/tawanj.jpg",
    "lat": 27.5861,
    "lng": 91.8667,
    "significance": "Major Gelugpa monastery founded in the 17th century",
    "bestTimeToVisit": "March to October"
  },
   
  {
    "id": "anandpur-sahib",
    "name": "Takht Sri Kesgarh Sahib",
    "location": "Anandpur Sahib, Punjab",
    "religion": "Sikh",
    "description": "Historic gurdwara where the Khalsa was founded in 1699",
    "image": "/kesgarh.jpg",
    "lat": 31.2396,
    "lng": 76.5026,
    "significance": "One of the five Takhts of Sikhism; founded by Guru Gobind Singh",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "patna-sahib",
    "name": "Takht Sri Patna Sahib",
    "location": "Patna, Bihar",
    "religion": "Sikh",
    "description": "Birthplace of Guru Gobind Singh and major Sikh pilgrimage site",
    "image": "/patha.jpg",
    "lat": 25.5941,
    "lng": 85.1376,
    "significance": "One of the five Takhts and sacred birthplace of the tenth Sikh Guru",
    "bestTimeToVisit": "October to March"
  },
  {
    "id": "hazur-sahib",
    "name": "Takht Sri Hazur Sahib",
    "location": "Nanded, Maharashtra",
    "religion": "Sikh",
    "description": "Sacred gurdwara where Guru Gobind Singh spent his final days",
    "image": "/htazur.jpg",
    "lat": 19.1383,
    "lng": 77.3210,
    "significance": "One of the five Takhts; site of Guru Gobind Singh’s passing",
    "bestTimeToVisit": "October to February"
  },
  
  {
    "id": "bangla-sahib",
    "name": "Gurudwara Bangla Sahib",
    "location": "New Delhi, India",
    "religion": "Sikh",
    "description": "Prominent gurdwara known for its golden dome and sacred sarovar",
    "image": "/gurubangla.jpg",
    "lat": 28.6264,
    "lng": 77.2091,
    "significance": "Associated with Guru Har Krishan and known for community service (langar)",
    "bestTimeToVisit": "October to March"
  }
]



export function getPilgrimagesByReligion(religion: string): PilgrimagePlace[] {
  return pilgrimagePlaces.filter((place) => place.religion === religion);
}

export function getAllReligions(): string[] {
  return Array.from(new Set(pilgrimagePlaces.map((place) => place.religion)));
}